//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DataStorage.SerializableStringDictionary Reflectors {
            get {
                return ((global::DataStorage.SerializableStringDictionary)(this["Reflectors"]));
            }
            set {
                this["Reflectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DataStorage.SerializableStringDictionary Commuters {
            get {
                return ((global::DataStorage.SerializableStringDictionary)(this["Commuters"]));
            }
            set {
                this["Commuters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DataStorage.SerializableStringDictionary Rotors {
            get {
                return ((global::DataStorage.SerializableStringDictionary)(this["Rotors"]));
            }
            set {
                this["Rotors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DataStorage.SerializableStringDictionary AppResourses {
            get {
                return ((global::DataStorage.SerializableStringDictionary)(this["AppResourses"]));
            }
            set {
                this["AppResourses"] = value;
            }
        }
    }
}
